;;; tests/origami-fold-test.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'origami)
(require 'drag-stuff)
(require 'org)
(require 'org-fold)

(defun luyangliuable-test/origami-close-at (needle)
  "Close the Origami node found forward from NEEDLE."
  (goto-char (point-min))
  (search-forward needle)
  (origami-close-node-recursively (current-buffer) (point)))

(defun luyangliuable-test/origami-node-at-point ()
  "Return the deepest Origami node found at or after point on its line."
  (car (last (origami-search-forward-for-path (current-buffer) (point)))))

(ert-deftest luyangliuable-test/origami-moves-nested-fold-and-recloses-it ()
  (with-temp-buffer
    (c-mode)
    (insert "before;\nvoid parent() {\n  if (ready) {\n    child();\n  }\n}\nafter;\n")
    (font-lock-ensure)
    (origami-mode 1)
    (luyangliuable-test/origami-close-at "void parent")
    (should (eq (luyangliuable/drag-closed-origami-fold #'drag-stuff-down)
                'moved))
    (should (equal (buffer-string)
                   "before;\nafter;\nvoid parent() {\n  if (ready) {\n    child();\n  }\n}\n"))
    (should-not (origami-fold-open?
                 (luyangliuable/origami-closed-node-at-point)))
    (should (eq (luyangliuable/drag-closed-origami-fold #'drag-stuff-up)
                'moved))
    (should (equal (buffer-string)
                   "before;\nvoid parent() {\n  if (ready) {\n    child();\n  }\n}\nafter;\n"))
    (should-not (origami-fold-open?
                 (luyangliuable/origami-closed-node-at-point)))))

(ert-deftest luyangliuable-test/origami-recloses-exact-same-line-node ()
  (with-temp-buffer
    (c-mode)
    (insert "before;\nvoid parent() { if (ready) { child(); } }\nafter;\n")
    (font-lock-ensure)
    (origami-mode 1)
    (luyangliuable-test/origami-close-at "if (ready)")
    (should (eq (luyangliuable/drag-closed-origami-fold #'drag-stuff-down)
                'moved))
    (goto-char (point-min))
    (search-forward "if (ready)")
    (let* ((inner (luyangliuable-test/origami-node-at-point))
           (outer-path (origami-search-forward-for-path
                        (current-buffer)
                        (save-excursion
                          (search-backward "void parent")
                          (point))))
           (outer (cadr outer-path)))
      (should-not (origami-fold-open? inner))
      (should (origami-fold-open? outer)))))

(ert-deftest luyangliuable-test/origami-blocks-upper-buffer-boundary ()
  (with-temp-buffer
    (c-mode)
    (insert "void first() {\n  child();\n}\nafter;\n")
    (font-lock-ensure)
    (origami-mode 1)
    (luyangliuable-test/origami-close-at "void first")
    (let ((before (buffer-string)))
      (should (eq (luyangliuable/drag-closed-origami-fold #'drag-stuff-up)
                  'blocked))
      (should (equal before (buffer-string)))
      (should (luyangliuable/origami-closed-node-at-point)))))

(ert-deftest luyangliuable-test/origami-blocks-lower-buffer-boundary ()
  (dolist (suffix '("" "\n"))
    (with-temp-buffer
      (c-mode)
      (insert "before;\nvoid last() {\n  child();\n}" suffix)
      (font-lock-ensure)
      (origami-mode 1)
      (luyangliuable-test/origami-close-at "void last")
      (let ((before (buffer-string)))
        (should (eq (luyangliuable/drag-closed-origami-fold #'drag-stuff-down)
                    'blocked))
        (should (equal before (buffer-string)))
        (should (luyangliuable/origami-closed-node-at-point))))))

(ert-deftest luyangliuable-test/org-closes-subtree-from-planning-line ()
  (with-temp-buffer
    (org-mode)
    (insert "** DONE Deploy\nCLOSED: [2026-08-26 Wed 14:00]\n:PROPERTIES:\n:COUNT: 3\n:END:\n- Progress\n")
    (goto-char (point-min))
    (forward-line 1)
    (luyangliuable/close-fold-at-point)
    (goto-char (point-min))
    (should (org-fold-folded-p (line-end-position) 'headline))
    (luyangliuable/close-fold-at-point)
    (should (org-fold-folded-p (line-end-position) 'headline))))

(ert-deftest luyangliuable-test/org-closes-logbook-from-clock-line ()
  (with-temp-buffer
    (org-mode)
    (insert "* Task\n:LOGBOOK:\nCLOCK: [2026-08-19 Wed 11:30]--[2026-08-19 Wed 11:31] =>  0:01\n:END:\n")
    (goto-char (point-min))
    (search-forward "CLOCK:")
    (luyangliuable/close-fold-at-point)
    (goto-char (point-min))
    (forward-line 1)
    (should (org-fold-folded-p (line-end-position) 'drawer))
    (goto-char (point-min))
    (should-not (org-fold-folded-p (line-end-position) 'headline))))

(ert-deftest luyangliuable-test/org-closes-src-block-inside-drawer ()
  (with-temp-buffer
    (org-mode)
    (insert "* Task\n:EXECUTION_LOG:\n#+begin_src bash :eval never :results none\ndate +%Y-%m-%d\n#+end_src\n:END:\n")
    (goto-char (point-min))
    (search-forward "date +%Y")
    (luyangliuable/close-fold-at-point)
    (goto-char (point-min))
    (forward-line 2)
    (should (org-fold-folded-p (line-end-position) 'block))
    (forward-line -1)
    (should-not (org-fold-folded-p (line-end-position) 'drawer))))

(ert-deftest luyangliuable-test/org-closes-heading-from-property-drawer ()
  (with-temp-buffer
    (org-mode)
    (insert "* Parent\n** Child\n:PROPERTIES:\n:EFFORT: 1:00\n:END:\nBody\n")
    (goto-char (point-min))
    (search-forward ":EFFORT:")
    (luyangliuable/close-fold-at-point)
    (goto-char (point-min))
    (forward-line 1)
    (should (org-fold-folded-p (line-end-position) 'headline))
    (goto-char (point-min))
    (should-not (org-fold-folded-p (line-end-position) 'headline))))

(ert-deftest luyangliuable-test/org-closes-parent-from-child-heading ()
  (with-temp-buffer
    (org-mode)
    (insert "* Parent\n** Child\nBody\n** Sibling\n")
    (goto-char (point-min))
    (forward-line 1)
    (luyangliuable/close-fold-at-point)
    (goto-char (point-min))
    (should (org-fold-folded-p (line-end-position) 'headline))))

(ert-deftest luyangliuable-test/org-closes-execution-log-drawer ()
  (with-temp-buffer
    (org-mode)
    (insert "* Task\n:EXECUTION_LOG:\n- Executed: [2026-08-28 Fri 10:25]\n  - Purpose: Retry deployment.\n  - Result: Deployment queued.\n:END:\n")
    (goto-char (point-min))
    (search-forward "- Executed:")
    (forward-line 0)
    (luyangliuable/close-fold-at-point)
    (goto-char (point-min))
    (forward-line 1)
    (should (org-fold-folded-p (line-end-position) 'drawer))
    (save-excursion
      (search-forward "Purpose:")
      (should (org-fold-folded-p (point) 'drawer)))
    (goto-char (point-min))
    (should-not (org-fold-folded-p (line-end-position) 'headline))))

(ert-deftest luyangliuable-test/outline-closes-enclosing-heading ()
  (with-temp-buffer
    (outline-mode)
    (setq-local outline-regexp "\\*+ ")
    (insert "* Parent\n** Child\nBody\n")
    (goto-char (point-min))
    (search-forward "Body")
    (luyangliuable/close-fold-at-point)
    (goto-char (point-min))
    (forward-line 1)
    (should (outline-invisible-p (line-end-position)))))

(ert-deftest luyangliuable-test/org-moves-collapsed-subtree ()
  (with-temp-buffer
    (org-mode)
    (insert "* Before\n* Parent\n** Parent child\nBody\n* After\n** After child\n* Last\n")
    (goto-char (point-min))
    (forward-line 1)
    (org-fold-hide-subtree)
    (should (eq (luyangliuable/drag-org-subtree #'drag-stuff-down)
                'moved))
    (should (equal (buffer-string)
                   "* Before\n* After\n** After child\n* Parent\n** Parent child\nBody\n* Last\n"))
    (should (org-fold-folded-p (line-end-position) 'headline))))

(ert-deftest luyangliuable-test/org-moves-expanded-subtree ()
  (with-temp-buffer
    (org-mode)
    (insert "* Parent\n** Child\n* Sibling\n** Sibling child\n")
    (goto-char (point-min))
    (should (eq (luyangliuable/drag-org-subtree #'drag-stuff-down)
                'moved))
    (should (equal (buffer-string)
                   "* Sibling\n** Sibling child\n* Parent\n** Child\n"))))

(ert-deftest luyangliuable-test/drag-wrapper-falls-back-without-fold ()
  (with-temp-buffer
    (insert "first\nsecond\n")
    (goto-char (point-min))
    (luyangliuable/drag-stuff-down-repeatable)
    (should (equal (buffer-string) "second\nfirst\n"))))

(ert-deftest luyangliuable-test/origami-defers-to-active-region ()
  (with-temp-buffer
    (c-mode)
    (insert "before;\nvoid parent() {\n  child();\n}\nafter;\n")
    (font-lock-ensure)
    (origami-mode 1)
    (luyangliuable-test/origami-close-at "void parent")
    (set-mark (line-beginning-position))
    (forward-line 1)
    (activate-mark)
    (should (eq (luyangliuable/drag-closed-origami-fold #'drag-stuff-down)
                'no-fold))))
